#!/usr/bin/env bash
set -euo pipefail

rm -rf /usr/share/plasma/look-and-feel/org.fedoraproject.fedora.desktop/
rm -rf /usr/share/plasma/look-and-feel/org.fedoraproject.fedoradark.desktop/
rm -rf /usr/share/plasma/look-and-feel/org.fedoraproject.fedoralight.desktop/
rm -rf /usr/share/wallpapers/F*
rm -rf /usr/share/wallpapers/D*
rm -rf /usr/share/icons/oxygen/
rm -rf /usr/share/icons/Bluecurve/
rm -rf /usr/share/icons/locolor/
rm -rf /usr/share/backgrounds/
rm -rf /usr/share/deepin/
rm -rf /usr/share/fedora-logos/
rm -rf /usr/share/icewm/
rm -rf /usr/share/kde4/
#rm -rf /usr/share/icons/AdwaitaLegacy/
rm -rf /usr/share/icons/hicolor/16x16/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/22x22/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/24x24/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/32x32/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/36x36/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/48x48/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/96x96/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/256x256/apps/fedora-logo-icon.png
rm -rf /usr/share/icons/hicolor/16x16/places/start-here.png
rm -rf /usr/share/icons/hicolor/22x22/places/start-here.png
rm -rf /usr/share/icons/hicolor/24x24/places/start-here.png
rm -rf /usr/share/icons/hicolor/32x32/places/start-here.png
rm -rf /usr/share/icons/hicolor/36x36/places/start-here.png
rm -rf /usr/share/icons/hicolor/48x48/places/start-here.png
rm -rf /usr/share/icons/hicolor/96x96/places/start-here.png
rm -rf /usr/share/icons/hicolor/256x256/places/start-here.png